# Generated by Django 3.0.6 on 2020-05-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaussian', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='t',
        ),
        migrations.RemoveField(
            model_name='point',
            name='y',
        ),
    ]
