# Generated by Django 3.0.6 on 2020-05-26 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaussian', '0004_auto_20200526_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='y',
        ),
    ]
